=== LiskArchive/lisk-sdk/protocol-specs/schema/lisk_protocol_specs.schema.json
{
	"title": "LiskProtocolSpec",
	"description": "Schema specification for JSON specs output",
	"$id": "https://lisk.io/schemas/protocol_specs",
	"$schema": "http://json-schema.org/draft-07/schema#",
	"type": "object",
	"additionalProperties": false,
	"required": ["title", "summary", "runner", "handler", "testCases"],
	"properties": {
		"title": {
			"type": "string",
			"description": "A string type value giving a short title of the spec",
			"minLength": 10,
			"maxLength": 100
		},
		"summary": {
			"type": "string",
			"description": "A string type value explaining in detail purpose and value of the spec",
			"minLength": 25,
			"maxLength": 300
		},
		"runner": {
			"type": "string",
			"description": "A string identifier to point to a protocol spec name e.g. dpos, bft",
			"minLength": 3,
			"maxLength": 100,
			"pattern": "[a-z0-9_]*"
		},
		"handler": {
			"type": "string",
			"description": "A string value to differentiate between same identifier for protocol spec",
			"minLength": 3,
			"maxLength": 100,
			"pattern": "[a-z0-9_]*"
		},
		"config": {
			"$ref": "#/definitions/Config"
		},
		"testCases": {
			"type": "array",
			"description": "List down all test cases for current handler and runner",
			"items": {
				"$ref": "#/definitions/TestCase"
			}
		}
	},
	"definitions": {
		"Account": {
			"title": "Account",
			"description": "Schema to specify and validate account in JSON specs",
			"type": "object"
		},
		"Block": {
			"title": "Block",
			"description": "Schema to specify and validate blocks in JSON specs",
			"type": "object"
		},
		"State": {
			"title": "State",
			"description": "A JSON object represents basic chain state for individual spec to be executed.",
			"type": "object",
			"properties": {
				"chain": {
					"type": "array",
					"uniqueItems": true,
					"items": {
						"$ref": "#/definitions/Block"
					}
				},
				"accounts": {
					"type": "array",
					"uniqueItems": true,
					"items": {
						"$ref": "#/definitions/Account"
					}
				}
			}
		},
		"Config": {
			"title": "Config",
			"description": "A JSON object containing all necessary configurations for the environment in which these specs were generated and individual test case can be verified.",
			"type": "object",
			"additionalProperties": true,
			"required": [],
			"properties": {
				"initialState": {
					"$ref": "#/definitions/State"
				}
			}
		},
		"TestCase": {
			"title": "Schema for a single test case",
			"type": "object",
			"additionalProperties": false,
			"required": ["input", "output", "description"],
			"properties": {
				"description": {
					"type": "string",
					"minLength": 10,
					"maxLength": 300
				},
				"config": {
					"description": "Configuration for a single test case",
					"$ref": "#/definitions/Config"
				},
				"input": {
					"type": "object",
					"description": "Input must be specified as a single object. If its complex scenario, it should be divided to multiple to have simple input/output expectations.",
					"minProperties": 1
				},
				"output": {
					"type": "object",
					"description": "Output must be specified as a single object. If its complex scenario, it should be divided to multiple to have simple input/output expectations.",
					"required": [],
					"additionalProperties": true,
					"minProperties": 1,
					"properties": {
						"mutatedState": {
							"description": "Modified chain state",
							"$ref": "#/definitions/State"
						}
					}
				}
			}
		}
	}
}

=== LiskArchive/lisk-sdk/protocol-specs/generator_outputs/lisk_codec/arrays_encodings.json
{
	"title": "Encoding for arrays types supported by lisk-codec",
	"summary": "Examples of encoding arrays with lisk-codec",
	"config": {
		"network": "devnet"
	},
	"runner": "lisk_codec",
	"handler": "arrays_encodings",
	"testCases": [
		{
			"description": "Encoding of integers array",
			"input": {
				"object": {
					"list": [3, 1, 4, 1, 5, 9, 2, 6, 5]
				},
				"schema": {
					"type": "object",
					"$id": "/arraySchemaUint32",
					"properties": {
						"list": {
							"type": "array",
							"items": {
								"dataType": "uint32"
							},
							"fieldNumber": 1
						}
					}
				}
			},
			"output": {
				"value": "0a09030104010509020605"
			}
		},
		{
			"description": "Encoding of booleans array",
			"input": {
				"object": {
					"list": [true, true, false, true, false, false]
				},
				"schema": {
					"type": "object",
					"$id": "/arraySchemaBoolean",
					"properties": {
						"list": {
							"type": "array",
							"items": {
								"dataType": "boolean"
							},
							"fieldNumber": 1
						}
					}
				}
			},
			"output": {
				"value": "0a06010100010000"
			}
		},
		{
			"description": "arrayStrings of strings array",
			"input": {
				"object": {
					"list": ["lisk", "", "gogogog"]
				},
				"schema": {
					"type": "object",
					"$id": "/arraySchemaString",
					"properties": {
						"list": {
							"type": "array",
							"items": {
								"dataType": "string"
							},
							"fieldNumber": 1
						}
					}
				}
			},
			"output": {
				"value": "0a046c69736b0a000a07676f676f676f67"
			}
		},
		{
			"description": "Encoding of objects array",
			"input": {
				"object": {
					"list": [
						{
							"address": "e11a11364738225813f86ea85214400e5db08d6e",
							"amount": "100000"
						},
						{
							"address": "aa2a11364738225813f86ea85214400e5db08fff",
							"amount": "300000"
						}
					]
				},
				"schema": {
					"type": "object",
					"$id": "/arraySchemaObject",
					"properties": {
						"list": {
							"type": "array",
							"items": {
								"type": "object",
								"properties": {
									"address": {
										"dataType": "string",
										"fieldNumber": 1
									},
									"amount": {
										"dataType": "uint64",
										"fieldNumber": 2
									}
								}
							},
							"fieldNumber": 1
						}
					}
				}
			},
			"output": {
				"value": "0a2e0a286531316131313336343733383232353831336638366561383532313434303065356462303864366510a08d060a2e0a286161326131313336343733383232353831336638366561383532313434303065356462303866666610e0a712"
			}
		},
		{
			"description": "Encoding of empty array",
			"input": {
				"object": {
					"list": []
				},
				"schema": {
					"type": "object",
					"$id": "/arraySchemaUint32",
					"properties": {
						"list": {
							"type": "array",
							"items": {
								"dataType": "uint32"
							},
							"fieldNumber": 1
						}
					}
				}
			},
			"output": {
				"value": ""
			}
		}
	]
}

=== LiskArchive/lisk-sdk/protocol-specs/generator_outputs/block_processing_transfers/valid_block_processing_one_transfer_tx.json
{
	"title": "Valid block processing",
	"summary": "A valid block with a transfer transaction is processed",
	"config": {
		"network": "mainnet"
	},
	"runner": "block_processing_transfers",
	"handler": "valid_block_processing_one_transfer_tx",
	"testCases": [
		{
			"config": {
				"initialState": {
					"chain": [
						{
							"version": 1,
							"totalAmount": "5000000000",
							"totalFee": "10000000",
							"reward": "0",
							"timestamp": 10,
							"numberOfTransactions": 1,
							"payloadLength": 117,
							"previousBlock": "6524861224470851795",
							"generatorPublicKey": "addb0e15a44b0fdc6ff291be28d8c98f5551d0cd9218d749e30ddb87c6e31ca9",
							"transactions": [
								{
									"id": "13770683072257473810",
									"amount": "5000000000",
									"type": 0,
									"timestamp": 102702700,
									"senderPublicKey": "c094ebee7ec0c50ebee32918655e089f6e1a604b83bcaa760293c61e0f18ab6f",
									"senderId": "16313739661670634666L",
									"recipientId": "10881167371402274308L",
									"fee": "10000000",
									"signature": "464abe544bea2f536475c9f8408fba6084df10c4700019a99c3ded11953df78396891f32b92b4e8454d5fbe2758cf971f9bce594e40f5b0cdd78b5e70e876e0d",
									"signatures": [],
									"asset": {}
								}
							],
							"payloadHash": "123d64444b4b1bbfba75b499238cee9341f82e87047df78a2b414629a03e0e63",
							"blockSignature": "298092da8fd4cf4c9d03a9c717bcb81274bbf34e0e6e7039cce162ca266551160d4566e509143c2f109c3bf7fd43edf4551565039e3ed73e474e511ac23ddc04",
							"height": 2
						}
					],
					"accounts": [
						{
							"address": "16313739661670634666L",
							"publicKey": "c094ebee7ec0c50ebee32918655e089f6e1a604b83bcaa760293c61e0f18ab6f",
							"secondPublicKey": null,
							"username": null,
							"isDelegate": false,
							"secondSignature": false,
							"balance": 9999899990000000,
							"multiMin": 0,
							"multiLifetime": 0,
							"nameExist": false,
							"missedBlocks": 0,
							"producedBlocks": 0,
							"rank": null,
							"fees": 0,
							"rewards": 0,
							"vote": 0,
							"productivity": 0
						},
						{
							"address": "10881167371402274308L",
							"publicKey": "addb0e15a44b0fdc6ff291be28d8c98f5551d0cd9218d749e30ddb87c6e31ca9",
							"secondPublicKey": null,
							"username": "genesis_100",
							"isDelegate": true,
							"secondSignature": false,
							"balance": 0,
							"multiMin": 0,
							"multiLifetime": 0,
							"nameExist": false,
							"missedBlocks": 1,
							"producedBlocks": 0,
							"rank": 70,
							"fees": 0,
							"rewards": 0,
							"vote": 9999899990000000,
							"productivity": 0
						}
					]
				}
			},
			"description": "A valid block with a transfer transaction is processed",
			"input": {
				"version": 1,
				"totalAmount": "4000000000",
				"totalFee": "10000000",
				"reward": "0",
				"timestamp": 20,
				"numberOfTransactions": 1,
				"payloadLength": 117,
				"generatorPublicKey": "addb0e15a44b0fdc6ff291be28d8c98f5551d0cd9218d749e30ddb87c6e31ca9",
				"transactions": [
					{
						"id": "13571226364241390960",
						"amount": "4000000000",
						"type": 0,
						"timestamp": 102702700,
						"senderPublicKey": "addb0e15a44b0fdc6ff291be28d8c98f5551d0cd9218d749e30ddb87c6e31ca9",
						"senderId": "10881167371402274308L",
						"recipientId": "2222471382442610527L",
						"fee": "10000000",
						"signature": "ed6ca09502e49dfd87959392faec9600dc0bba96a80e927f4219f7c6954766e0c35ae0209528107388c47b63608c9c2846f8b896c4645fba2dc6c14c13a2cc0c",
						"signatures": [],
						"asset": {}
					}
				],
				"payloadHash": "702d068f79ae56bc591c5e01b090df97ee71a593bdfb78a7e203d8c582d18e3f",
				"blockSignature": "189c7e0b4fbc73c19700a8b23e080110d280b1d2f2f1926abb98183a57939c3b292c672e169370dbbe98c4297c83a12f90c10775624626fb065d25e0b6c83f00",
				"height": 3
			},
			"output": {
				"chain": [
					{
						"version": 1,
						"totalAmount": "5000000000",
						"totalFee": "10000000",
						"reward": "0",
						"timestamp": 10,
						"numberOfTransactions": 1,
						"payloadLength": 117,
						"previousBlock": "6524861224470851795",
						"generatorPublicKey": "addb0e15a44b0fdc6ff291be28d8c98f5551d0cd9218d749e30ddb87c6e31ca9",
						"transactions": [
							{
								"id": "13770683072257473810",
								"amount": "5000000000",
								"type": 0,
								"timestamp": 102702700,
								"senderPublicKey": "c094ebee7ec0c50ebee32918655e089f6e1a604b83bcaa760293c61e0f18ab6f",
								"senderId": "16313739661670634666L",
								"recipientId": "10881167371402274308L",
								"fee": "10000000",
								"signature": "464abe544bea2f536475c9f8408fba6084df10c4700019a99c3ded11953df78396891f32b92b4e8454d5fbe2758cf971f9bce594e40f5b0cdd78b5e70e876e0d",
								"signatures": [],
								"asset": {}
							}
						],
						"payloadHash": "123d64444b4b1bbfba75b499238cee9341f82e87047df78a2b414629a03e0e63",
						"blockSignature": "298092da8fd4cf4c9d03a9c717bcb81274bbf34e0e6e7039cce162ca266551160d4566e509143c2f109c3bf7fd43edf4551565039e3ed73e474e511ac23ddc04",
						"height": 2
					},
					{
						"version": 1,
						"totalAmount": "4000000000",
						"totalFee": "10000000",
						"reward": "0",
						"timestamp": 20,
						"numberOfTransactions": 1,
						"payloadLength": 117,
						"generatorPublicKey": "addb0e15a44b0fdc6ff291be28d8c98f5551d0cd9218d749e30ddb87c6e31ca9",
						"transactions": [
							{
								"id": "13571226364241390960",
								"amount": "4000000000",
								"type": 0,
								"timestamp": 102702700,
								"senderPublicKey": "addb0e15a44b0fdc6ff291be28d8c98f5551d0cd9218d749e30ddb87c6e31ca9",
								"senderId": "10881167371402274308L",
								"recipientId": "2222471382442610527L",
								"fee": "10000000",
								"signature": "ed6ca09502e49dfd87959392faec9600dc0bba96a80e927f4219f7c6954766e0c35ae0209528107388c47b63608c9c2846f8b896c4645fba2dc6c14c13a2cc0c",
								"signatures": [],
								"asset": {}
							}
						],
						"payloadHash": "702d068f79ae56bc591c5e01b090df97ee71a593bdfb78a7e203d8c582d18e3f",
						"blockSignature": "189c7e0b4fbc73c19700a8b23e080110d280b1d2f2f1926abb98183a57939c3b292c672e169370dbbe98c4297c83a12f90c10775624626fb065d25e0b6c83f00",
						"height": 3
					}
				],
				"accounts": [
					[
						{
							"address": "16313739661670634666L",
							"publicKey": "c094ebee7ec0c50ebee32918655e089f6e1a604b83bcaa760293c61e0f18ab6f",
							"secondPublicKey": null,
							"username": null,
							"isDelegate": false,
							"secondSignature": false,
							"balance": "9999894980000000",
							"multiMin": 0,
							"multiLifetime": 0,
							"nameExist": false,
							"missedBlocks": 0,
							"producedBlocks": 0,
							"rank": null,
							"fees": 0,
							"rewards": 0,
							"vote": 0,
							"productivity": 0
						},
						{
							"address": "10881167371402274308L",
							"publicKey": "addb0e15a44b0fdc6ff291be28d8c98f5551d0cd9218d749e30ddb87c6e31ca9",
							"secondPublicKey": null,
							"username": "genesis_100",
							"isDelegate": true,
							"secondSignature": false,
							"balance": "990000000",
							"multiMin": 0,
							"multiLifetime": 0,
							"nameExist": false,
							"missedBlocks": 1,
							"producedBlocks": 0,
							"rank": 70,
							"fees": 0,
							"rewards": 0,
							"vote": 9999899990000000,
							"productivity": 0
						},
						{
							"address": "2222471382442610527L",
							"publicKey": "caff2242b740a733daa3f3f96fc1592303b60c1704a8ac626e2704da039f41ee",
							"secondPublicKey": null,
							"username": "",
							"isDelegate": false,
							"secondSignature": false,
							"balance": "4000000000",
							"multiMin": 0,
							"multiLifetime": 0,
							"nameExist": false,
							"missedBlocks": 0,
							"producedBlocks": 0,
							"rank": 0,
							"fees": 0,
							"rewards": 0,
							"vote": 0,
							"productivity": 0
						}
					]
				]
			}
		}
	]
}

=== LiskArchive/lisk-sdk/protocol-specs/generator_outputs/transaction_network_id_and_change_order/delegate_transaction_validate.json
{
	"title": "Valid delegate transaction",
	"summary": "A valid delegate transaction",
	"config": {
		"network": "devnet"
	},
	"runner": "transaction_network_id_and_change_order",
	"handler": "delegate_transaction_validate",
	"testCases": [
		{
			"description": "A valid delegate transaction",
			"input": {
				"account": {
					"passphrase": "wear protect skill sentence lift enter wild sting lottery power floor neglect",
					"privateKey": "8f41ff1e75c4f0f8a71bae4952266928d0e91660fc513566ac694fed61157497efaf1d977897cb60d7db9d30e8fd668dee070ac0db1fb8d184c06152a8b75f8d",
					"publicKey": "efaf1d977897cb60d7db9d30e8fd668dee070ac0db1fb8d184c06152a8b75f8d",
					"address": "2129300327344985743L"
				},
				"networkIdentifier": "e48feb88db5b5cf5ad71d93cdcd1d879b6d5ed187a36b0002cc34e0ef9883255",
				"transaction": {
					"type": 10,
					"senderPublicKey": "efaf1d977897cb60d7db9d30e8fd668dee070ac0db1fb8d184c06152a8b75f8d",
					"timestamp": 54316335,
					"asset": {
						"username": "new_delegate"
					}
				}
			},
			"output": {
				"type": 10,
				"senderPublicKey": "efaf1d977897cb60d7db9d30e8fd668dee070ac0db1fb8d184c06152a8b75f8d",
				"timestamp": 54316335,
				"asset": {
					"username": "new_delegate"
				},
				"signature": "50041721c3317058bf454f15de169e666f4f363b22532e204336fd620918f9ef4698411407d96ce9242fb3a5107f2113bb1b48234c63f1f836fc6b7c37b7d002",
				"id": "5726885376730735876"
			}
		}
	]
}

=== LiskArchive/lisk-sdk/protocol-specs/generator_outputs/lisk_codec/peer_info_sample_encoding.json
{
	"title": "Encondings for a peer info object",
	"summary": "Example of encoding a peer info object for p2p",
	"config": {
		"network": "devnet"
	},
	"runner": "lisk_codec",
	"handler": "peer_info_sample_encoding",
	"testCases": [
		{
			"description": "Encoding of peer info sample",
			"input": {
				"object": {
					"ipAddress": "1.1.1.1",
					"wsPort": 1111,
					"networkIdentifier": "f8fe7ecc3e29f58f39d8a538f9a35b80b4b6ab9674f0300e25e33ff41274ae32",
					"networkVersion": "2.0",
					"nonce": "iNIgD0Mb3s/RMaXbs",
					"os": "darwin",
					"height": 123
				},
				"schema": {
					"$id": "peerInfo",
					"type": "object",
					"properties": {
						"ipAddress": {
							"dataType": "string",
							"fieldNumber": 1
						},
						"wsPort": {
							"dataType": "uint32",
							"fieldNumber": 2
						},
						"networkIdentifier": {
							"dataType": "string",
							"fieldNumber": 3
						},
						"networkVersion": {
							"dataType": "string",
							"fieldNumber": 4
						},
						"nonce": {
							"dataType": "string",
							"fieldNumber": 5
						},
						"os": {
							"dataType": "string",
							"fieldNumber": 6
						},
						"height": {
							"dataType": "uint32",
							"fieldNumber": 7
						}
					},
					"required": ["ipAddress", "wsPort"]
				}
			},
			"output": {
				"value": "0a07312e312e312e3110d7081a40663866653765636333653239663538663339643861353338663961333562383062346236616239363734663033303065323565333366663431323734616533322203322e302a11694e496744304d6233732f524d61586273320664617277696e387b"
			}
		},
		{
			"description": "Encoding of peer info sample with optional property",
			"input": {
				"object": {
					"ipAddress": "1.1.1.1",
					"wsPort": 1111,
					"os": "darwin"
				},
				"schema": {
					"$id": "peerInfo",
					"type": "object",
					"properties": {
						"ipAddress": {
							"dataType": "string",
							"fieldNumber": 1
						},
						"wsPort": {
							"dataType": "uint32",
							"fieldNumber": 2
						},
						"networkIdentifier": {
							"dataType": "string",
							"fieldNumber": 3
						},
						"networkVersion": {
							"dataType": "string",
							"fieldNumber": 4
						},
						"nonce": {
							"dataType": "string",
							"fieldNumber": 5
						},
						"os": {
							"dataType": "string",
							"fieldNumber": 6
						},
						"height": {
							"dataType": "uint32",
							"fieldNumber": 7
						}
					},
					"required": ["ipAddress", "wsPort"]
				}
			},
			"output": {
				"value": "0a07312e312e312e3110d708320664617277696e"
			}
		}
	]
}

=== LiskArchive/lisk-sdk/protocol-specs/generator_outputs/lisk_codec/block_decodings.json
{
	"title": "Decoding for block types supported by lisk-codec",
	"summary": "Examples of encoding block with lisk-codec",
	"config": {
		"network": "devnet"
	},
	"runner": "lisk_codec",
	"handler": "block_decodings",
	"testCases": [
		{
			"description": "Decoding of valid block with payload",
			"input": {
				"value": "0a20ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad1220a665a45920422f9d417e4867efdc4fb8a04a1f3fff1fa07e998e86f7f7a27ae3122068a751863fe73b8ede8d832be628ff680d617fa15c74d00142f9025d5f37dd50",
				"schema": {
					"$id": "/blockSchema",
					"type": "object",
					"properties": {
						"header": {
							"dataType": "bytes",
							"fieldNumber": 1
						},
						"payload": {
							"type": "array",
							"items": {
								"dataType": "bytes"
							},
							"fieldNumber": 2
						}
					},
					"required": ["header", "payload"]
				}
			},
			"output": {
				"object": {
					"header": "ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad",
					"payload": [
						"a665a45920422f9d417e4867efdc4fb8a04a1f3fff1fa07e998e86f7f7a27ae3",
						"68a751863fe73b8ede8d832be628ff680d617fa15c74d00142f9025d5f37dd50"
					]
				}
			}
		},
		{
			"description": "Decoding of valid block block without payload",
			"input": {
				"value": "0a20e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
				"schema": {
					"$id": "/blockSchema",
					"type": "object",
					"properties": {
						"header": {
							"dataType": "bytes",
							"fieldNumber": 1
						},
						"payload": {
							"type": "array",
							"items": {
								"dataType": "bytes"
							},
							"fieldNumber": 2
						}
					},
					"required": ["header", "payload"]
				}
			},
			"output": {
				"object": {
					"header": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
					"payload": []
				}
			}
		}
	]
}

=== LiskArchive/lisk-sdk/protocol-specs/generator_outputs/lisk_codec/bytes_decodings.json
{
	"title": "Decoding for bytes types supported by lisk-codec",
	"summary": "Examples of encoding bytes with lisk-codec",
	"config": {
		"network": "devnet"
	},
	"runner": "lisk_codec",
	"handler": "bytes_decodings",
	"testCases": [
		{
			"description": "Decoding of chunk of bytes",
			"input": {
				"value": "0a14e11a11364738225813f86ea85214400e5db08d6e",
				"schema": {
					"$id": "/object9",
					"type": "object",
					"properties": {
						"address": {
							"dataType": "bytes",
							"fieldNumber": 1
						}
					}
				}
			},
			"output": {
				"object": {
					"address": "e11a11364738225813f86ea85214400e5db08d6e"
				}
			}
		},
		{
			"description": "Decoding of empty bytes",
			"input": {
				"value": "0a00",
				"schema": {
					"$id": "/object9",
					"type": "object",
					"properties": {
						"address": {
							"dataType": "bytes",
							"fieldNumber": 1
						}
					}
				}
			},
			"output": {
				"object": {
					"address": ""
				}
			}
		}
	]
}

=== LiskArchive/lisk-sdk/protocol-specs/generator_outputs/lisk_codec/block_encodings.json
{
	"title": "Encondings for block types supported by lisk-codec",
	"summary": "Examples of encoding block with lisk-codec",
	"config": {
		"network": "devnet"
	},
	"runner": "lisk_codec",
	"handler": "block_encodings",
	"testCases": [
		{
			"description": "Encoding of valid block with payload",
			"input": {
				"object": {
					"header": {
						"type": "Buffer",
						"data": [
							186,
							120,
							22,
							191,
							143,
							1,
							207,
							234,
							65,
							65,
							64,
							222,
							93,
							174,
							34,
							35,
							176,
							3,
							97,
							163,
							150,
							23,
							122,
							156,
							180,
							16,
							255,
							97,
							242,
							0,
							21,
							173
						]
					},
					"payload": [
						{
							"type": "Buffer",
							"data": [
								166,
								101,
								164,
								89,
								32,
								66,
								47,
								157,
								65,
								126,
								72,
								103,
								239,
								220,
								79,
								184,
								160,
								74,
								31,
								63,
								255,
								31,
								160,
								126,
								153,
								142,
								134,
								247,
								247,
								162,
								122,
								227
							]
						},
						{
							"type": "Buffer",
							"data": [
								104,
								167,
								81,
								134,
								63,
								231,
								59,
								142,
								222,
								141,
								131,
								43,
								230,
								40,
								255,
								104,
								13,
								97,
								127,
								161,
								92,
								116,
								208,
								1,
								66,
								249,
								2,
								93,
								95,
								55,
								221,
								80
							]
						}
					]
				},
				"schema": {
					"$id": "blockSchema",
					"type": "object",
					"properties": {
						"header": {
							"dataType": "bytes",
							"fieldNumber": 1
						},
						"payload": {
							"type": "array",
							"items": {
								"dataType": "bytes"
							},
							"fieldNumber": 2
						}
					},
					"required": [
						"header",
						"payload"
					]
				}
			},
			"output": {
				"value": "0a20ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad1220a665a45920422f9d417e4867efdc4fb8a04a1f3fff1fa07e998e86f7f7a27ae3122068a751863fe73b8ede8d832be628ff680d617fa15c74d00142f9025d5f37dd50"
			}
		},
		{
			"description": "Encoding of valid block block without payload",
			"input": {
				"object": {
					"header": {
						"type": "Buffer",
						"data": [
							227,
							176,
							196,
							66,
							152,
							252,
							28,
							20,
							154,
							251,
							244,
							200,
							153,
							111,
							185,
							36,
							39,
							174,
							65,
							228,
							100,
							155,
							147,
							76,
							164,
							149,
							153,
							27,
							120,
							82,
							184,
							85
						]
					},
					"payload": []
				},
				"schema": {
					"$id": "blockSchema",
					"type": "object",
					"properties": {
						"header": {
							"dataType": "bytes",
							"fieldNumber": 1
						},
						"payload": {
							"type": "array",
							"items": {
								"dataType": "bytes"
							},
							"fieldNumber": 2
						}
					},
					"required": [
						"header",
						"payload"
					]
				}
			},
			"output": {
				"value": "0a20e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"
			}
		}
	]
}

=== LiskArchive/lisk-sdk/protocol-specs/generator_outputs/transaction_network_id_and_change_order/multi_signature_transaction_validate.json
{
	"title": "Valid multi signature transaction",
	"summary": "A valid multi signature transaction",
	"config": {
		"network": "devnet"
	},
	"runner": "transaction_network_id_and_change_order",
	"handler": "multi_signature_transaction_validate",
	"testCases": [
		{
			"description": "A valid multi signature transaction",
			"input": {
				"account": {
					"passphrase": "wear protect skill sentence lift enter wild sting lottery power floor neglect",
					"privateKey": "8f41ff1e75c4f0f8a71bae4952266928d0e91660fc513566ac694fed61157497efaf1d977897cb60d7db9d30e8fd668dee070ac0db1fb8d184c06152a8b75f8d",
					"publicKey": "efaf1d977897cb60d7db9d30e8fd668dee070ac0db1fb8d184c06152a8b75f8d",
					"address": "2129300327344985743L"
				},
				"networkIdentifier": "e48feb88db5b5cf5ad71d93cdcd1d879b6d5ed187a36b0002cc34e0ef9883255",
				"coSigners": [
					{
						"passphrase": "inherit moon normal relief spring bargain hobby join baby flash fog blood",
						"privateKey": "de4a28610239ceac2ec3f592e36a2ead8ed4ac93cb16aa0d996ab6bb0249da2c0b211fce4b615083701cb8a8c99407e464b2f9aa4f367095322de1b77e5fcfbe",
						"publicKey": "0b211fce4b615083701cb8a8c99407e464b2f9aa4f367095322de1b77e5fcfbe",
						"address": "18141291412139607230L"
					},
					{
						"passphrase": "better across runway mansion jar route valid crack panic favorite smooth sword",
						"privateKey": "de1520f8589408e76a97643ba7d27f20009b06899816c8af20f9b03f4a4bd8a66766ce280eb99e45d2cc7d9c8c852720940dab5d69f480e80477a97b4255d5d8",
						"publicKey": "6766ce280eb99e45d2cc7d9c8c852720940dab5d69f480e80477a97b4255d5d8",
						"address": "13191770412077040757L"
					},
					{
						"passphrase": "mirror swap middle hunt angle furnace maid scheme amazing box bachelor debris",
						"privateKey": "ad7462eb8f682b0c3424213ead044381ba0007bb65ce26287fc308027c871d951387d8ec6306807ffd6fe27ea3443985765c1157928bb09904307956f46a9972",
						"publicKey": "1387d8ec6306807ffd6fe27ea3443985765c1157928bb09904307956f46a9972",
						"address": "2443122499609067441L"
					}
				],
				"transaction": {
					"type": 12,
					"senderPublicKey": "efaf1d977897cb60d7db9d30e8fd668dee070ac0db1fb8d184c06152a8b75f8d",
					"timestamp": 44316326,
					"asset": {
						"min": 2,
						"lifetime": 22,
						"keysgroup": [
							"+0b211fce4b615083701cb8a8c99407e464b2f9aa4f367095322de1b77e5fcfbe",
							"+6766ce280eb99e45d2cc7d9c8c852720940dab5d69f480e80477a97b4255d5d8",
							"+1387d8ec6306807ffd6fe27ea3443985765c1157928bb09904307956f46a9972"
						]
					}
				}
			},
			"output": {
				"type": 12,
				"senderPublicKey": "efaf1d977897cb60d7db9d30e8fd668dee070ac0db1fb8d184c06152a8b75f8d",
				"timestamp": 44316326,
				"asset": {
					"min": 2,
					"lifetime": 22,
					"keysgroup": [
						"+0b211fce4b615083701cb8a8c99407e464b2f9aa4f367095322de1b77e5fcfbe",
						"+6766ce280eb99e45d2cc7d9c8c852720940dab5d69f480e80477a97b4255d5d8",
						"+1387d8ec6306807ffd6fe27ea3443985765c1157928bb09904307956f46a9972"
					]
				},
				"signature": "b61560c6fa4bd20e0d561208911c89f6a9e2dc14f287886953e3f538473722759b42c5378f199e654fcea935088dd3c2b3f75d87c9f7c112ce8967ff15b3e60e",
				"signatures": [
					"fd1bc70422631e936019eaa7be4f8bc886dacd6711992c62354bc27eb161648f1d454dc12d2c6c607d6d3c7f4290e8de575f4fabf46a3ea2c62c8a135b4f2304",
					"66f3ea07fca295241fa49b01ada88baf9c8f394363e1d0230d5adacfe75692fcc2e6f698f934e9509e44e88701e9faf7203f826064ab33f57683d3137de3310e",
					"3b9dbe7ad5ef2cd2dc915e7230456e9d40520492eec32f46a874cad1497d9e10c42859cbd95f6e671abd708a977c6c9ecdfe326a1e24eeaa56fb28801d0de70e"
				],
				"id": "13937567402168253247"
			}
		}
	]
}
