=== LiskArchive/lisk-sdk/protocol-specs/schema/lisk_protocol_specs.schema.json
{
	"title": "LiskProtocolSpec",
	"description": "Schema specification for JSON specs output",
	"$id": "https://lisk.io/schemas/protocol_specs",
	"$schema": "http://json-schema.org/draft-07/schema#",
	"type": "object",
	"additionalProperties": false,
	"required": ["title", "summary", "runner", "handler", "testCases"],
	"properties": {
		"title": {
			"type": "string",
			"description": "A string type value giving a short title of the spec",
			"minLength": 10,
			"maxLength": 100
		},
		"summary": {
			"type": "string",
			"description": "A string type value explaining in detail purpose and value of the spec",
			"minLength": 25,
			"maxLength": 300
		},
		"runner": {
			"type": "string",
			"description": "A string identifier to point to a protocol spec name e.g. dpos, bft",
			"minLength": 3,
			"maxLength": 100,
			"pattern": "[a-z0-9_]*"
		},
		"handler": {
			"type": "string",
			"description": "A string value to differentiate between same identifier for protocol spec",
			"minLength": 3,
			"maxLength": 100,
			"pattern": "[a-z0-9_]*"
		},
		"config": {
			"$ref": "#/definitions/Config"
		},
		"testCases": {
			"type": "array",
			"description": "List down all test cases for current handler and runner",
			"items": {
				"$ref": "#/definitions/TestCase"
			}
		}
	},
	"definitions": {
		"Account": {
			"title": "Account",
			"description": "Schema to specify and validate account in JSON specs",
			"type": "object"
		},
		"Block": {
			"title": "Block",
			"description": "Schema to specify and validate blocks in JSON specs",
			"type": "object"
		},
		"State": {
			"title": "State",
			"description": "A JSON object represents basic chain state for individual spec to be executed.",
			"type": "object",
			"properties": {
				"chain": {
					"type": "array",
					"uniqueItems": true,
					"items": {
						"$ref": "#/definitions/Block"
					}
				},
				"accounts": {
					"type": "array",
					"uniqueItems": true,
					"items": {
						"$ref": "#/definitions/Account"
					}
				}
			}
		},
		"Config": {
			"title": "Config",
			"description": "A JSON object containing all necessary configurations for the environment in which these specs were generated and individual test case can be verified.",
			"type": "object",
			"additionalProperties": true,
			"required": [],
			"properties": {
				"initialState": {
					"$ref": "#/definitions/State"
				}
			}
		},
		"TestCase": {
			"title": "Schema for a single test case",
			"type": "object",
			"additionalProperties": false,
			"required": ["input", "output", "description"],
			"properties": {
				"description": {
					"type": "string",
					"minLength": 10,
					"maxLength": 300
				},
				"config": {
					"description": "Configuration for a single test case",
					"$ref": "#/definitions/Config"
				},
				"input": {
					"type": "object",
					"description": "Input must be specified as a single object. If its complex scenario, it should be divided to multiple to have simple input/output expectations.",
					"minProperties": 1
				},
				"output": {
					"type": "object",
					"description": "Output must be specified as a single object. If its complex scenario, it should be divided to multiple to have simple input/output expectations.",
					"required": [],
					"additionalProperties": true,
					"minProperties": 1,
					"properties": {
						"mutatedState": {
							"description": "Modified chain state",
							"$ref": "#/definitions/State"
						}
					}
				}
			}
		}
	}
}

=== LiskArchive/lisk-sdk/protocol-specs/generator_outputs/lisk_codec/validStringEncodings.json
{
	"title": "Valid string encodings",
	"summary": "Examples of encoding strings as required by lisk-codec",
	"config": {
		"network": "devnet"
	},
	"runner": "lisk_codec",
	"handler": "validStringEncodings",
	"testCases": [
		{
			"description": "Encoding of string types",
			"config": {
				"network": "devnet"
			},
			"input": {
				"string": {
					"object": {
						"data": "Checkout Lisk SDK!"
					},
					"schema": {
						"$id": "object7",
						"type": "object",
						"properties": {
							"data": {
								"dataType": "string",
								"fieldNumber": 1
							}
						}
					}
				},
				"emptyString": {
					"object": {
						"data": ""
					},
					"schema": {
						"$id": "object8",
						"type": "object",
						"properties": {
							"data": {
								"dataType": "string",
								"fieldNumber": 1
							}
						}
					}
				}
			},
			"output": {
				"string": "0a12436865636b6f7574204c69736b2053444b21",
				"emptyString": "0a00"
			}
		}
	]
}

=== LiskArchive/lisk-sdk/protocol-specs/generator_outputs/lisk_codec/validArrayEncodings.json
{
	"title": "Valid array encodings",
	"summary": "Examples of encoding arrays as required by lisk-codec",
	"config": {
		"network": "devnet"
	},
	"runner": "lisk_codec",
	"handler": "validArrayEncodings",
	"testCases": [
		{
			"description": "Encoding of boolean types",
			"config": {
				"network": "devnet"
			},
			"input": {
				"arrayInts": {
					"object": {
						"list": [
							3,
							1,
							4,
							1,
							5,
							9,
							2,
							6,
							5
						]
					},
					"schema": {
						"type": "object",
						"properties": {
							"list": {
								"dataType": "array",
								"fieldNumber": 1
							}
						}
					}
				},
				"arrayBools": {
					"object": {
						"list": [
							true,
							true,
							false,
							true,
							false,
							false
						]
					},
					"schema": {
						"type": "object",
						"properties": {
							"list": {
								"dataType": "array",
								"fieldNumber": 1
							}
						}
					}
				},
				"arrayOfObjects": {
					"object": {
						"myArray": [
							{
								"address": "e11a11364738225813f86ea85214400e5db08d6e",
								"amount": 100000
							},
							{
								"address": "aa2a11364738225813f86ea85214400e5db08fff",
								"amount": 300000
							}
						]
					},
					"schema": {
						"schema": {
							"type": "object",
							"properties": {
								"list": {
									"dataType": "array",
									"fieldNumber": 1,
									"items": {
										"type": "object",
										"properties": {
											"address": {
												"dataType": "string",
												"fieldNumber": 1
											},
											"amount": {
												"dataType": "uint64",
												"fieldNumber": 2
											}
										}
									}
								}
							}
						}
					}
				},
				"emptyArray": {
					"object": {
						"list": []
					},
					"schema": {
						"type": "object",
						"properties": {
							"list": {
								"dataType": "array",
								"fieldNumber": 1
							}
						}
					}
				}
			},
			"output": {
				"arrayIntsEncoded": "0a09030104010509020605",
				"arrayBoolsEncoded": "0a06010100010000",
				"arrayOfObjectsEncoded": "0a2e0a286531316131313336343733383232353831336638366561383532313434303065356462303864366510a08d060a2e0a286161326131313336343733383232353831336638366561383532313434303065356462303866666610e0a712",
				"emptyArrayEncoded": ""
			}
		}
	]
}

=== LiskArchive/lisk-sdk/protocol-specs/generator_outputs/bft_processing/4_delegates_simple.json
{
	"title": "BFT processing generation",
	"summary": "Generate status of pre-votes, pre-commits, finalized height and pre-voted height  as per BFT specification",
	"config": {
		"activeDelegates": 4,
		"finalizedHeight": 0
	},
	"runner": "bft_processing",
	"handler": "4_delegates_simple",
	"testCases": [
		{
			"description": "When block with height 1 is forged",
			"input": {
				"delegateName": "D1",
				"blockHeader": {
					"blockId": "7748076420210162913",
					"height": 1,
					"maxHeightPreviouslyForged": 0,
					"delegatePublicKey": "6352b9c9d2a263eaa701b53314e3021607d41e1ba6d799270f08adcba50841b7",
					"delegateMinHeightActive": 1,
					"maxHeightPrevoted": 0
				}
			},
			"output": {
				"finalizedHeight": 0,
				"preVotedConfirmedHeight": 0,
				"preVotes": {
					"1": 1
				},
				"preCommits": {}
			}
		},
		{
			"description": "When block with height 2 is forged",
			"input": {
				"delegateName": "D2",
				"blockHeader": {
					"blockId": "15308683162207262446",
					"height": 2,
					"maxHeightPreviouslyForged": 0,
					"delegatePublicKey": "f7a73f303f46ada157ce3cea5ffff1290a291e255fcd26678a185fd8aee33054",
					"delegateMinHeightActive": 1,
					"maxHeightPrevoted": 0
				}
			},
			"output": {
				"finalizedHeight": 0,
				"preVotedConfirmedHeight": 0,
				"preVotes": {
					"1": 2,
					"2": 1
				},
				"preCommits": {}
			}
		},
		{
			"description": "When block with height 3 is forged",
			"input": {
				"delegateName": "D3",
				"blockHeader": {
					"blockId": "5622533601426856843",
					"height": 3,
					"maxHeightPreviouslyForged": 0,
					"delegatePublicKey": "544d87cbf83b7c1572bb0d9f95abd5db89d0930bbb91980ea0dd7942a1cd38a3",
					"delegateMinHeightActive": 1,
					"maxHeightPrevoted": 0
				}
			},
			"output": {
				"finalizedHeight": 0,
				"preVotedConfirmedHeight": 1,
				"preVotes": {
					"1": 3,
					"2": 2,
					"3": 1
				},
				"preCommits": {}
			}
		},
		{
			"description": "When block with height 4 is forged",
			"input": {
				"delegateName": "D4",
				"blockHeader": {
					"blockId": "5414021058608832454",
					"height": 4,
					"maxHeightPreviouslyForged": 0,
					"delegatePublicKey": "c2d2f82c6015fd7ed00a9e1585927a8039d63cb7afd4f7c03ad059a93c2bd6b5",
					"delegateMinHeightActive": 1,
					"maxHeightPrevoted": 1
				}
			},
			"output": {
				"finalizedHeight": 0,
				"preVotedConfirmedHeight": 2,
				"preVotes": {
					"1": 4,
					"2": 3,
					"3": 2,
					"4": 1
				},
				"preCommits": {
					"1": 1
				}
			}
		},
		{
			"description": "When block with height 5 is forged",
			"input": {
				"delegateName": "D1",
				"blockHeader": {
					"blockId": "17234451680913495083",
					"height": 5,
					"maxHeightPreviouslyForged": 1,
					"delegatePublicKey": "6352b9c9d2a263eaa701b53314e3021607d41e1ba6d799270f08adcba50841b7",
					"delegateMinHeightActive": 1,
					"maxHeightPrevoted": 2
				}
			},
			"output": {
				"finalizedHeight": 0,
				"preVotedConfirmedHeight": 3,
				"preVotes": {
					"1": 4,
					"2": 4,
					"3": 3,
					"4": 2,
					"5": 1
				},
				"preCommits": {
					"1": 2,
					"2": 1
				}
			}
		},
		{
			"description": "When block with height 6 is forged",
			"input": {
				"delegateName": "D2",
				"blockHeader": {
					"blockId": "16714758248282885559",
					"height": 6,
					"maxHeightPreviouslyForged": 2,
					"delegatePublicKey": "f7a73f303f46ada157ce3cea5ffff1290a291e255fcd26678a185fd8aee33054",
					"delegateMinHeightActive": 1,
					"maxHeightPrevoted": 3
				}
			},
			"output": {
				"finalizedHeight": 1,
				"preVotedConfirmedHeight": 4,
				"preVotes": {
					"1": 4,
					"2": 4,
					"3": 4,
					"4": 3,
					"5": 2,
					"6": 1
				},
				"preCommits": {
					"1": 3,
					"2": 2,
					"3": 1
				}
			}
		},
		{
			"description": "When block with height 7 is forged",
			"input": {
				"delegateName": "D3",
				"blockHeader": {
					"blockId": "8719647946811673230",
					"height": 7,
					"maxHeightPreviouslyForged": 3,
					"delegatePublicKey": "544d87cbf83b7c1572bb0d9f95abd5db89d0930bbb91980ea0dd7942a1cd38a3",
					"delegateMinHeightActive": 1,
					"maxHeightPrevoted": 4
				}
			},
			"output": {
				"finalizedHeight": 2,
				"preVotedConfirmedHeight": 5,
				"preVotes": {
					"1": 4,
					"2": 4,
					"3": 4,
					"4": 4,
					"5": 3,
					"6": 2,
					"7": 1
				},
				"preCommits": {
					"1": 4,
					"2": 3,
					"3": 2,
					"4": 1
				}
			}
		},
		{
			"description": "When block with height 8 is forged",
			"input": {
				"delegateName": "D4",
				"blockHeader": {
					"blockId": "3198191471355371895",
					"height": 8,
					"maxHeightPreviouslyForged": 4,
					"delegatePublicKey": "c2d2f82c6015fd7ed00a9e1585927a8039d63cb7afd4f7c03ad059a93c2bd6b5",
					"delegateMinHeightActive": 1,
					"maxHeightPrevoted": 5
				}
			},
			"output": {
				"finalizedHeight": 3,
				"preVotedConfirmedHeight": 6,
				"preVotes": {
					"1": 4,
					"2": 4,
					"3": 4,
					"4": 4,
					"5": 4,
					"6": 3,
					"7": 2,
					"8": 1
				},
				"preCommits": {
					"1": 4,
					"2": 4,
					"3": 3,
					"4": 2,
					"5": 1
				}
			}
		},
		{
			"description": "When block with height 9 is forged",
			"input": {
				"delegateName": "D1",
				"blockHeader": {
					"blockId": "1826242805484023040",
					"height": 9,
					"maxHeightPreviouslyForged": 5,
					"delegatePublicKey": "6352b9c9d2a263eaa701b53314e3021607d41e1ba6d799270f08adcba50841b7",
					"delegateMinHeightActive": 1,
					"maxHeightPrevoted": 6
				}
			},
			"output": {
				"finalizedHeight": 4,
				"preVotedConfirmedHeight": 7,
				"preVotes": {
					"1": 4,
					"2": 4,
					"3": 4,
					"4": 4,
					"5": 4,
					"6": 4,
					"7": 3,
					"8": 2,
					"9": 1
				},
				"preCommits": {
					"1": 4,
					"2": 4,
					"3": 4,
					"4": 3,
					"5": 2,
					"6": 1
				}
			}
		},
		{
			"description": "When block with height 10 is forged",
			"input": {
				"delegateName": "D2",
				"blockHeader": {
					"blockId": "5351644240885712040",
					"height": 10,
					"maxHeightPreviouslyForged": 6,
					"delegatePublicKey": "f7a73f303f46ada157ce3cea5ffff1290a291e255fcd26678a185fd8aee33054",
					"delegateMinHeightActive": 1,
					"maxHeightPrevoted": 7
				}
			},
			"output": {
				"finalizedHeight": 5,
				"preVotedConfirmedHeight": 8,
				"preVotes": {
					"1": 4,
					"2": 4,
					"3": 4,
					"4": 4,
					"5": 4,
					"6": 4,
					"7": 4,
					"8": 3,
					"9": 2,
					"10": 1
				},
				"preCommits": {
					"1": 4,
					"2": 4,
					"3": 4,
					"4": 4,
					"5": 3,
					"6": 2,
					"7": 1
				}
			}
		},
		{
			"description": "When block with height 11 is forged",
			"input": {
				"delegateName": "D3",
				"blockHeader": {
					"blockId": "5748892369479747538",
					"height": 11,
					"maxHeightPreviouslyForged": 7,
					"delegatePublicKey": "544d87cbf83b7c1572bb0d9f95abd5db89d0930bbb91980ea0dd7942a1cd38a3",
					"delegateMinHeightActive": 1,
					"maxHeightPrevoted": 8
				}
			},
			"output": {
				"finalizedHeight": 6,
				"preVotedConfirmedHeight": 9,
				"preVotes": {
					"1": 4,
					"2": 4,
					"3": 4,
					"4": 4,
					"5": 4,
					"6": 4,
					"7": 4,
					"8": 4,
					"9": 3,
					"10": 2,
					"11": 1
				},
				"preCommits": {
					"1": 4,
					"2": 4,
					"3": 4,
					"4": 4,
					"5": 4,
					"6": 3,
					"7": 2,
					"8": 1
				}
			}
		},
		{
			"description": "When block with height 12 is forged",
			"input": {
				"delegateName": "D4",
				"blockHeader": {
					"blockId": "7733195345837784852",
					"height": 12,
					"maxHeightPreviouslyForged": 8,
					"delegatePublicKey": "c2d2f82c6015fd7ed00a9e1585927a8039d63cb7afd4f7c03ad059a93c2bd6b5",
					"delegateMinHeightActive": 1,
					"maxHeightPrevoted": 9
				}
			},
			"output": {
				"finalizedHeight": 7,
				"preVotedConfirmedHeight": 10,
				"preVotes": {
					"1": 4,
					"2": 4,
					"3": 4,
					"4": 4,
					"5": 4,
					"6": 4,
					"7": 4,
					"8": 4,
					"9": 4,
					"10": 3,
					"11": 2,
					"12": 1
				},
				"preCommits": {
					"1": 4,
					"2": 4,
					"3": 4,
					"4": 4,
					"5": 4,
					"6": 4,
					"7": 3,
					"8": 2,
					"9": 1
				}
			}
		}
	]
}

=== LiskArchive/lisk-sdk/protocol-specs/generator_outputs/transaction_signing/valid_transaction_signing.json
{
	"title": "Valid signature generation",
	"summary": "based on a valid transfer transaction generate a signature an id for it",
	"config": {
		"network": "mainnet"
	},
	"runner": "transaction_signing",
	"handler": "valid_transaction_signing",
	"testCases": [
		{
			"description": "Test case for valid transaction signature",
			"input": {
				"transferTransaction": {
					"amount": "10",
					"recipientId": "17819145097849555674L",
					"timestamp": 100565431,
					"asset": {},
					"fee": "10000000",
					"type": 0
				},
				"senderPassphrase": "movie tiger belt popular bridge dish frozen fragile quit high pass coconut"
			},
			"output": {
				"signature": "579164b3045a612823b2b9ec667374417565229a4028f905b8452bf91048633f9a679d49fc46169659f3f3329ad414e8c6e17e1c2f9866a6e1bee9efa2a60a0a"
			}
		}
	]
}

=== LiskArchive/lisk-sdk/protocol-specs/generator_outputs/lisk_codec/transaction_encodings.json
{
	"title": "Encoding for transaction types supported by lisk-codec",
	"summary": "Examples of encoding transaction with lisk-codec",
	"config": {
		"network": "devnet"
	},
	"runner": "lisk_codec",
	"handler": "transaction_encodings",
	"testCases": [
		{
			"description": "Encoding of valid base transaction",
			"input": {
				"object": {
					"moduleID": 20,
					"assetID": 1,
					"nonce": "1570179673932370",
					"fee": "3156364651",
					"senderPublicKey": "8f057d088a585d938c20d63e430a068d4cea384e588aa0b758c68fca21644dbc",
					"asset": "f214d75bbc4b2ea89e433f3a45af803725416ec3",
					"signatures": [
						"204514eb1152355799ece36d17037e5feb4871472c60763bdafe67eb6a38bec632a8e2e62f84a32cf764342a4708a65fbad194e37feec03940f0ff84d3df2a05",
						"0b6730e5898ca56fe0dc1c73de9363f6fc8b335592ef10725a8463bff101a4943e60311f0b1a439a2c9e02cca1379b80a822f4ec48cf212bff1f1c757e92ec02"
					]
				},
				"schema": {
					"$id": "baseTransactionSchema",
					"type": "object",
					"properties": {
						"moduleID": {
							"dataType": "uint32",
							"fieldNumber": 1
						},
						"assetID": {
							"dataType": "uint32",
							"fieldNumber": 2
						},
						"nonce": {
							"dataType": "uint64",
							"fieldNumber": 3
						},
						"fee": {
							"dataType": "uint64",
							"fieldNumber": 4
						},
						"senderPublicKey": {
							"dataType": "bytes",
							"fieldNumber": 5
						},
						"asset": {
							"dataType": "bytes",
							"fieldNumber": 6
						},
						"signatures": {
							"type": "array",
							"items": {
								"dataType": "bytes"
							},
							"fieldNumber": 7
						}
					},
					"required": [
						"moduleID",
						"assetID",
						"nonce",
						"fee",
						"senderPublicKey",
						"asset",
						"signatures"
					]
				}
			},
			"output": {
				"value": "0814100118d284cb8d9f82e50220eb9a89e10b2a208f057d088a585d938c20d63e430a068d4cea384e588aa0b758c68fca21644dbc3214f214d75bbc4b2ea89e433f3a45af803725416ec33a40204514eb1152355799ece36d17037e5feb4871472c60763bdafe67eb6a38bec632a8e2e62f84a32cf764342a4708a65fbad194e37feec03940f0ff84d3df2a053a400b6730e5898ca56fe0dc1c73de9363f6fc8b335592ef10725a8463bff101a4943e60311f0b1a439a2c9e02cca1379b80a822f4ec48cf212bff1f1c757e92ec02"
			}
		},
		{
			"description": "Encoding of valid stake asset",
			"input": {
				"object": {
					"stakes": [
						{
							"validatorAddress": "cd32c73e9851c7137980063b8af64aa5a31651f8",
							"amount": "-12000000000"
						},
						{
							"validatorAddress": "9d86ad24a3f030e5522b6598115bb4d70c1692c9",
							"amount": "456000000000"
						}
					]
				},
				"schema": {
					"$id": "voteAssetSchema",
					"type": "object",
					"properties": {
						"stakes": {
							"type": "array",
							"fieldNumber": 1,
							"items": {
								"type": "object",
								"properties": {
									"validatorAddress": {
										"dataType": "bytes",
										"fieldNumber": 1
									},
									"amount": {
										"dataType": "sint64",
										"fieldNumber": 2
									}
								},
								"required": ["validatorAddress", "amount"]
							}
						}
					},
					"required": ["stakes"]
				}
			},
			"output": {
				"value": "0a1c0a14cd32c73e9851c7137980063b8af64aa5a31651f810ffdf8bb4590a1d0a149d86ad24a3f030e5522b6598115bb4d70c1692c91080c0bebbc51a"
			}
		},
		{
			"description": "Encoding of valid multisignature asset",
			"input": {
				"object": {
					"numberOfSignatures": 2,
					"mandatoryKeys": [
						"07d6389be6e2109613699c02e78253148989515c3867e4f490eafd004a95b2b4",
						"3e754d00815b6b248a981520afbaf913153a26d25e2d5283964779c65ceee7e8"
					],
					"optionalKeys": [
						"c8b8fbe474a2b63ccb9744a409569b0a465ee1803f80435aec1c5e7fc2d4ee18",
						"6115424fec0ce9c3bac5a81b5c782827d1f956fb95f1ccfa36c566d04e4d7267"
					]
				},
				"schema": {
					"$id": "multisigAssetSchema",
					"type": "object",
					"properties": {
						"numberOfSignatures": {
							"dataType": "uint32",
							"fieldNumber": 1
						},
						"mandatoryKeys": {
							"type": "array",
							"items": {
								"dataType": "bytes"
							},
							"fieldNumber": 2
						},
						"optionalKeys": {
							"type": "array",
							"items": {
								"dataType": "bytes"
							},
							"fieldNumber": 3
						}
					},
					"required": ["numberOfSignatures", "mandatoryKeys", "optionalKeys"]
				}
			},
			"output": {
				"value": "0802122007d6389be6e2109613699c02e78253148989515c3867e4f490eafd004a95b2b412203e754d00815b6b248a981520afbaf913153a26d25e2d5283964779c65ceee7e81a20c8b8fbe474a2b63ccb9744a409569b0a465ee1803f80435aec1c5e7fc2d4ee181a206115424fec0ce9c3bac5a81b5c782827d1f956fb95f1ccfa36c566d04e4d7267"
			}
		},
		{
			"description": "Encoding of valid multisignature asset with empty array",
			"input": {
				"object": {
					"numberOfSignatures": 2,
					"mandatoryKeys": [
						"c8b8fbe474a2b63ccb9744a409569b0a465ee1803f80435aec1c5e7fc2d4ee18",
						"6115424fec0ce9c3bac5a81b5c782827d1f956fb95f1ccfa36c566d04e4d7267"
					],
					"optionalKeys": []
				},
				"schema": {
					"$id": "multisigAssetSchema",
					"type": "object",
					"properties": {
						"numberOfSignatures": {
							"dataType": "uint32",
							"fieldNumber": 1
						},
						"mandatoryKeys": {
							"type": "array",
							"items": {
								"dataType": "bytes"
							},
							"fieldNumber": 2
						},
						"optionalKeys": {
							"type": "array",
							"items": {
								"dataType": "bytes"
							},
							"fieldNumber": 3
						}
					},
					"required": ["numberOfSignatures", "mandatoryKeys", "optionalKeys"]
				}
			},
			"output": {
				"value": "08021220c8b8fbe474a2b63ccb9744a409569b0a465ee1803f80435aec1c5e7fc2d4ee1812206115424fec0ce9c3bac5a81b5c782827d1f956fb95f1ccfa36c566d04e4d7267"
			}
		}
	]
}

=== LiskArchive/lisk-sdk/protocol-specs/generator_outputs/transaction_network_id_and_change_order/transfer_transaction_with_multi_signature_validate.json
{
	"title": "Valid transfer transaction with multi signature",
	"summary": "A valid transfer transaction with multi signature",
	"config": {
		"network": "devnet"
	},
	"runner": "transaction_network_id_and_change_order",
	"handler": "transfer_transaction_with_multi_signature_validate",
	"testCases": [
		{
			"description": "A valid transfer transaction with multi signature",
			"input": {
				"account": {
					"passphrase": "wear protect skill sentence lift enter wild sting lottery power floor neglect",
					"privateKey": "8f41ff1e75c4f0f8a71bae4952266928d0e91660fc513566ac694fed61157497efaf1d977897cb60d7db9d30e8fd668dee070ac0db1fb8d184c06152a8b75f8d",
					"publicKey": "efaf1d977897cb60d7db9d30e8fd668dee070ac0db1fb8d184c06152a8b75f8d",
					"address": "2129300327344985743L"
				},
				"coSigners": [
					{
						"passphrase": "better across runway mansion jar route valid crack panic favorite smooth sword",
						"privateKey": "de1520f8589408e76a97643ba7d27f20009b06899816c8af20f9b03f4a4bd8a66766ce280eb99e45d2cc7d9c8c852720940dab5d69f480e80477a97b4255d5d8",
						"publicKey": "6766ce280eb99e45d2cc7d9c8c852720940dab5d69f480e80477a97b4255d5d8",
						"address": "13191770412077040757L"
					},
					{
						"passphrase": "mirror swap middle hunt angle furnace maid scheme amazing box bachelor debris",
						"privateKey": "ad7462eb8f682b0c3424213ead044381ba0007bb65ce26287fc308027c871d951387d8ec6306807ffd6fe27ea3443985765c1157928bb09904307956f46a9972",
						"publicKey": "1387d8ec6306807ffd6fe27ea3443985765c1157928bb09904307956f46a9972",
						"address": "2443122499609067441L"
					}
				],
				"networkIdentifier": "e48feb88db5b5cf5ad71d93cdcd1d879b6d5ed187a36b0002cc34e0ef9883255",
				"transaction": {
					"type": 8,
					"senderPublicKey": "efaf1d977897cb60d7db9d30e8fd668dee070ac0db1fb8d184c06152a8b75f8d",
					"timestamp": 54316325,
					"asset": {
						"recipientId": "18141291412139607230L",
						"amount": "1234567890",
						"data": "random data"
					}
				}
			},
			"output": {
				"type": 8,
				"senderPublicKey": "efaf1d977897cb60d7db9d30e8fd668dee070ac0db1fb8d184c06152a8b75f8d",
				"timestamp": 54316325,
				"asset": {
					"recipientId": "18141291412139607230L",
					"amount": "1234567890",
					"data": "random data"
				},
				"signature": "b88d0408318d3bf700586116046c9101535ee76d2d4b6a5903ac31f5d302094ad4b08180105ff91882482d5d62ca48ba2ed281b75134b90110e1a98aed7efe0d",
				"signatures": [
					"4424342c342093f80f52f919876fc0abada5385e98e8caf211add16d1c0f5453ef6e47fa58a454128a9640f3b6e2ade618e5ee5fa8eebc4d68460d19f042050f",
					"014cae10ddd5f482f8b99f8eb5699721fa795be0806118555282a304ea6a84510b1e3ec8675347c2a70f6c5abc29dc17160b94cc3cedec9f88eb1acf027ced02"
				],
				"id": "3436168030012755419"
			}
		}
	]
}
