=== LiskArchive/lisk-sdk/protocol-specs/schema/lisk_protocol_specs.schema.json
{
	"title": "LiskProtocolSpec",
	"description": "Schema specification for JSON specs output",
	"$id": "https://lisk.io/schemas/protocol_specs",
	"$schema": "http://json-schema.org/draft-07/schema#",
	"type": "object",
	"additionalProperties": false,
	"required": ["title", "summary", "runner", "handler", "testCases"],
	"properties": {
		"title": {
			"type": "string",
			"description": "A string type value giving a short title of the spec",
			"minLength": 10,
			"maxLength": 100
		},
		"summary": {
			"type": "string",
			"description": "A string type value explaining in detail purpose and value of the spec",
			"minLength": 25,
			"maxLength": 300
		},
		"runner": {
			"type": "string",
			"description": "A string identifier to point to a protocol spec name e.g. dpos, bft",
			"minLength": 3,
			"maxLength": 100,
			"pattern": "[a-z0-9_]*"
		},
		"handler": {
			"type": "string",
			"description": "A string value to differentiate between same identifier for protocol spec",
			"minLength": 3,
			"maxLength": 100,
			"pattern": "[a-z0-9_]*"
		},
		"config": {
			"$ref": "#/definitions/Config"
		},
		"testCases": {
			"type": "array",
			"description": "List down all test cases for current handler and runner",
			"items": {
				"$ref": "#/definitions/TestCase"
			}
		}
	},
	"definitions": {
		"Account": {
			"title": "Account",
			"description": "Schema to specify and validate account in JSON specs",
			"type": "object"
		},
		"Block": {
			"title": "Block",
			"description": "Schema to specify and validate blocks in JSON specs",
			"type": "object"
		},
		"State": {
			"title": "State",
			"description": "A JSON object represents basic chain state for individual spec to be executed.",
			"type": "object",
			"properties": {
				"chain": {
					"type": "array",
					"uniqueItems": true,
					"items": {
						"$ref": "#/definitions/Block"
					}
				},
				"accounts": {
					"type": "array",
					"uniqueItems": true,
					"items": {
						"$ref": "#/definitions/Account"
					}
				}
			}
		},
		"Config": {
			"title": "Config",
			"description": "A JSON object containing all necessary configurations for the environment in which these specs were generated and individual test case can be verified.",
			"type": "object",
			"additionalProperties": true,
			"required": [],
			"properties": {
				"initialState": {
					"$ref": "#/definitions/State"
				}
			}
		},
		"TestCase": {
			"title": "Schema for a single test case",
			"type": "object",
			"additionalProperties": false,
			"required": ["input", "output", "description"],
			"properties": {
				"description": {
					"type": "string",
					"minLength": 10,
					"maxLength": 300
				},
				"config": {
					"description": "Configuration for a single test case",
					"$ref": "#/definitions/Config"
				},
				"input": {
					"type": "object",
					"description": "Input must be specified as a single object. If its complex scenario, it should be divided to multiple to have simple input/output expectations.",
					"minProperties": 1
				},
				"output": {
					"type": "object",
					"description": "Output must be specified as a single object. If its complex scenario, it should be divided to multiple to have simple input/output expectations.",
					"required": [],
					"additionalProperties": true,
					"minProperties": 1,
					"properties": {
						"mutatedState": {
							"description": "Modified chain state",
							"$ref": "#/definitions/State"
						}
					}
				}
			}
		}
	}
}

=== LiskArchive/lisk-sdk/protocol-specs/generator_outputs/lisk_codec/genesis_block_encodings.json
{
	"title": "Encoding for genesis block types supported by lisk-codec",
	"summary": "Examples of encoding block with lisk-codec",
	"config": {
		"network": "devnet"
	},
	"runner": "lisk_codec",
	"handler": "genesis_block_encodings",
	"testCases": [
		{
			"description": "Encoding of valid genesis block asset",
			"input": {
				"object": {
					"initValidators": [
						"03f6d90b7dbd0497dc3a52d1c27e23bb8c75897f",
						"0903f4c5cb599a7928aef27e314e98291d1e3888",
						"0ada6a2f6c8f891769366fc9aa6fd9f1facb36cf"
					],
					"initRounds": 3,
					"accounts": [
						{
							"address": "03f6d90b7dbd0497dc3a52d1c27e23bb8c75897f",
							"publicKey": "fc65777c1d4c00f1af5880c23ba7f60cd3bf84d1bf5c697abc4ffe17cf7acac0",
							"balance": "0",
							"nonce": "0",
							"keys": {
								"mandatoryKeys": [],
								"optionalKeys": [],
								"numberOfSignatures": 0
							},
							"asset": {
								"validator": {
									"username": "genesis_34",
									"pomHeights": [],
									"consecutiveMissedBlocks": 0,
									"lastForgedHeight": 0,
									"isBanned": false,
									"totalStakeReceived": "1000000000000"
								},
								"sentStakes": [
									{
										"validatorAddress": "03f6d90b7dbd0497dc3a52d1c27e23bb8c75897f",
										"amount": "1000000000000"
									}
								],
								"unlocking": []
							}
						},
						{
							"address": "0903f4c5cb599a7928aef27e314e98291d1e3888",
							"publicKey": "3f571324e9dc7b2481b71a7dc56637f1234504158986a242e90c33d8d20fdd92",
							"balance": "0",
							"nonce": "0",
							"keys": {
								"mandatoryKeys": [],
								"optionalKeys": [],
								"numberOfSignatures": 0
							},
							"asset": {
								"validator": {
									"username": "genesis_74",
									"pomHeights": [],
									"consecutiveMissedBlocks": 0,
									"lastForgedHeight": 0,
									"isBanned": false,
									"totalStakeReceived": "1000000000000"
								},
								"sentStakes": [],
								"unlocking": []
							}
						},
						{
							"address": "0ada6a2f6c8f891769366fc9aa6fd9f1facb36cf",
							"publicKey": "c69698ef30012964aafacfbe637bb63854b6109cc5c5f22aa4b3dc3e8dca8217",
							"balance": "0",
							"nonce": "0",
							"keys": {
								"mandatoryKeys": [],
								"optionalKeys": [],
								"numberOfSignatures": 0
							},
							"asset": {
								"validator": {
									"username": "genesis_98",
									"pomHeights": [],
									"consecutiveMissedBlocks": 0,
									"lastForgedHeight": 0,
									"isBanned": false,
									"totalStakeReceived": "1000000000000"
								},
								"sentStakes": [
									{
										"validatorAddress": "0ada6a2f6c8f891769366fc9aa6fd9f1facb36cf",
										"amount": "1000000000000"
									}
								],
								"unlocking": []
							}
						}
					]
				},
				"schema": {
					"$id": "/genesisBlockAssetSchema",
					"type": "object",
					"required": ["accounts", "initValidators", "initRounds"],
					"properties": {
						"accounts": {
							"type": "array",
							"items": {
								"type": "object",
								"properties": {
									"address": {
										"dataType": "bytes",
										"fieldNumber": 1
									},
									"balance": {
										"dataType": "uint64",
										"fieldNumber": 2
									},
									"publicKey": {
										"dataType": "bytes",
										"fieldNumber": 3
									},
									"nonce": {
										"dataType": "uint64",
										"fieldNumber": 4
									},
									"keys": {
										"fieldNumber": 5,
										"type": "object",
										"properties": {
											"numberOfSignatures": {
												"dataType": "uint32",
												"fieldNumber": 1
											},
											"mandatoryKeys": {
												"type": "array",
												"items": {
													"dataType": "bytes"
												},
												"fieldNumber": 2
											},
											"optionalKeys": {
												"type": "array",
												"items": {
													"dataType": "bytes"
												},
												"fieldNumber": 3
											}
										},
										"required": ["numberOfSignatures", "mandatoryKeys", "optionalKeys"]
									},
									"asset": {
										"fieldNumber": 6,
										"type": "object",
										"properties": {
											"validator": {
												"type": "object",
												"fieldNumber": 1,
												"properties": {
													"username": {
														"dataType": "string",
														"fieldNumber": 1
													},
													"pomHeights": {
														"type": "array",
														"items": {
															"dataType": "uint32"
														},
														"fieldNumber": 2
													},
													"consecutiveMissedBlocks": {
														"dataType": "uint32",
														"fieldNumber": 3
													},
													"lastForgedHeight": {
														"dataType": "uint32",
														"fieldNumber": 4
													},
													"isBanned": {
														"dataType": "boolean",
														"fieldNumber": 5
													},
													"totalStakeReceived": {
														"dataType": "uint64",
														"fieldNumber": 6
													}
												},
												"required": [
													"username",
													"pomHeights",
													"consecutiveMissedBlocks",
													"lastForgedHeight",
													"isBanned",
													"totalStakeReceived"
												]
											},
											"sentStakes": {
												"type": "array",
												"fieldNumber": 2,
												"items": {
													"type": "object",
													"properties": {
														"validatorAddress": {
															"dataType": "bytes",
															"fieldNumber": 1
														},
														"amount": {
															"dataType": "uint64",
															"fieldNumber": 2
														}
													},
													"required": ["validatorAddress", "amount"]
												}
											},
											"unlocking": {
												"type": "array",
												"fieldNumber": 3,
												"items": {
													"type": "object",
													"properties": {
														"validatorAddress": {
															"dataType": "bytes",
															"fieldNumber": 1
														},
														"amount": {
															"dataType": "uint64",
															"fieldNumber": 2
														},
														"unstakeHeight": {
															"dataType": "uint32",
															"fieldNumber": 3
														}
													},
													"required": ["validatorAddress", "amount", "unstakeHeight"]
												}
											}
										}
									}
								},
								"required": ["address", "balance", "publicKey", "nonce", "keys", "asset"]
							},
							"fieldNumber": 1
						},
						"initValidators": {
							"type": "array",
							"items": {
								"dataType": "bytes"
							},
							"fieldNumber": 2
						},
						"initRounds": {
							"dataType": "uint32",
							"fieldNumber": 3,
							"minimum": 3
						}
					}
				}
			},
			"output": {
				"value": "0a7c0a1403f6d90b7dbd0497dc3a52d1c27e23bb8c75897f10001a20fc65777c1d4c00f1af5880c23ba7f60cd3bf84d1bf5c697abc4ffe17cf7acac020002a020800323a0a190a0a67656e657369735f33341800200028003080a094a58d1d121d0a1403f6d90b7dbd0497dc3a52d1c27e23bb8c75897f1080a094a58d1d0a5d0a140903f4c5cb599a7928aef27e314e98291d1e388810001a203f571324e9dc7b2481b71a7dc56637f1234504158986a242e90c33d8d20fdd9220002a020800321b0a190a0a67656e657369735f37341800200028003080a094a58d1d0a7c0a140ada6a2f6c8f891769366fc9aa6fd9f1facb36cf10001a20c69698ef30012964aafacfbe637bb63854b6109cc5c5f22aa4b3dc3e8dca821720002a020800323a0a190a0a67656e657369735f39381800200028003080a094a58d1d121d0a140ada6a2f6c8f891769366fc9aa6fd9f1facb36cf1080a094a58d1d121403f6d90b7dbd0497dc3a52d1c27e23bb8c75897f12140903f4c5cb599a7928aef27e314e98291d1e388812140ada6a2f6c8f891769366fc9aa6fd9f1facb36cf1803"
			}
		}
	]
}

=== LiskArchive/lisk-sdk/protocol-specs/generator_outputs/lisk_codec/block_asset_decodings.json
{
	"title": "Decoding for block asset types supported by lisk-codec",
	"summary": "Examples of encoding block asset with lisk-codec",
	"config": {
		"network": "devnet"
	},
	"runner": "lisk_codec",
	"handler": "block_asset_decodings",
	"testCases": [
		{
			"description": "Decoding of valid block asset",
			"input": {
				"value": "08990810b9ff361a10d59386e0ae435e292fbe0ebcdb954b75",
				"schema": {
					"$id": "/blockAssetSchema",
					"type": "object",
					"properties": {
						"maxHeightPreviouslyForged": {
							"dataType": "uint32",
							"fieldNumber": 1
						},
						"maxHeightPrevoted": {
							"dataType": "uint32",
							"fieldNumber": 2
						},
						"seedReveal": {
							"dataType": "bytes",
							"fieldNumber": 3
						}
					},
					"required": ["maxHeightPreviouslyForged", "maxHeightPrevoted", "seedReveal"]
				}
			},
			"output": {
				"object": {
					"maxHeightPreviouslyForged": 1049,
					"maxHeightPrevoted": 901049,
					"seedReveal": "d59386e0ae435e292fbe0ebcdb954b75"
				}
			}
		},
		{
			"description": "Decoding of valid block asset with zero previously forged",
			"input": {
				"value": "08001099081a10eaaf9d4c65cb501c811ef812847a5551",
				"schema": {
					"$id": "/blockAssetSchema",
					"type": "object",
					"properties": {
						"maxHeightPreviouslyForged": {
							"dataType": "uint32",
							"fieldNumber": 1
						},
						"maxHeightPrevoted": {
							"dataType": "uint32",
							"fieldNumber": 2
						},
						"seedReveal": {
							"dataType": "bytes",
							"fieldNumber": 3
						}
					},
					"required": ["maxHeightPreviouslyForged", "maxHeightPrevoted", "seedReveal"]
				}
			},
			"output": {
				"object": {
					"maxHeightPreviouslyForged": 0,
					"maxHeightPrevoted": 1049,
					"seedReveal": "eaaf9d4c65cb501c811ef812847a5551"
				}
			}
		}
	]
}

=== LiskArchive/lisk-sdk/protocol-specs/generator_outputs/bft_processing/4_validators_simple.json
{
	"title": "BFT processing generation",
	"summary": "Generate status of pre-votes, pre-commits, finalized height and pre-voted height  as per BFT specification",
	"config": {
		"activeValidators": 4,
		"finalizedHeight": 0
	},
	"runner": "bft_processing",
	"handler": "4_validators_simple",
	"testCases": [
		{
			"description": "When block with height 1 is forged",
			"input": {
				"validatorName": "D1",
				"blockHeader": {
					"id": "7748076420210162913",
					"height": 1,
					"maxHeightPreviouslyForged": 0,
					"generatorPublicKey": "6352b9c9d2a263eaa701b53314e3021607d41e1ba6d799270f08adcba50841b7",
					"validatorMinHeightActive": 1,
					"maxHeightPrevoted": 0
				}
			},
			"output": {
				"finalizedHeight": 0,
				"preVotedConfirmedHeight": 0,
				"preVotes": {
					"1": 1
				},
				"preCommits": {}
			}
		},
		{
			"description": "When block with height 2 is forged",
			"input": {
				"validatorName": "D2",
				"blockHeader": {
					"id": "15308683162207262446",
					"height": 2,
					"maxHeightPreviouslyForged": 0,
					"generatorPublicKey": "f7a73f303f46ada157ce3cea5ffff1290a291e255fcd26678a185fd8aee33054",
					"validatorMinHeightActive": 1,
					"maxHeightPrevoted": 0
				}
			},
			"output": {
				"finalizedHeight": 0,
				"preVotedConfirmedHeight": 0,
				"preVotes": {
					"1": 2,
					"2": 1
				},
				"preCommits": {}
			}
		},
		{
			"description": "When block with height 3 is forged",
			"input": {
				"validatorName": "D3",
				"blockHeader": {
					"id": "5622533601426856843",
					"height": 3,
					"maxHeightPreviouslyForged": 0,
					"generatorPublicKey": "544d87cbf83b7c1572bb0d9f95abd5db89d0930bbb91980ea0dd7942a1cd38a3",
					"validatorMinHeightActive": 1,
					"maxHeightPrevoted": 0
				}
			},
			"output": {
				"finalizedHeight": 0,
				"preVotedConfirmedHeight": 1,
				"preVotes": {
					"1": 3,
					"2": 2,
					"3": 1
				},
				"preCommits": {}
			}
		},
		{
			"description": "When block with height 4 is forged",
			"input": {
				"validatorName": "D4",
				"blockHeader": {
					"id": "5414021058608832454",
					"height": 4,
					"maxHeightPreviouslyForged": 0,
					"generatorPublicKey": "c2d2f82c6015fd7ed00a9e1585927a8039d63cb7afd4f7c03ad059a93c2bd6b5",
					"validatorMinHeightActive": 1,
					"maxHeightPrevoted": 1
				}
			},
			"output": {
				"finalizedHeight": 0,
				"preVotedConfirmedHeight": 2,
				"preVotes": {
					"1": 4,
					"2": 3,
					"3": 2,
					"4": 1
				},
				"preCommits": {
					"1": 1
				}
			}
		},
		{
			"description": "When block with height 5 is forged",
			"input": {
				"validatorName": "D1",
				"blockHeader": {
					"id": "17234451680913495083",
					"height": 5,
					"maxHeightPreviouslyForged": 1,
					"generatorPublicKey": "6352b9c9d2a263eaa701b53314e3021607d41e1ba6d799270f08adcba50841b7",
					"validatorMinHeightActive": 1,
					"maxHeightPrevoted": 2
				}
			},
			"output": {
				"finalizedHeight": 0,
				"preVotedConfirmedHeight": 3,
				"preVotes": {
					"1": 4,
					"2": 4,
					"3": 3,
					"4": 2,
					"5": 1
				},
				"preCommits": {
					"1": 2,
					"2": 1
				}
			}
		},
		{
			"description": "When block with height 6 is forged",
			"input": {
				"validatorName": "D2",
				"blockHeader": {
					"id": "16714758248282885559",
					"height": 6,
					"maxHeightPreviouslyForged": 2,
					"generatorPublicKey": "f7a73f303f46ada157ce3cea5ffff1290a291e255fcd26678a185fd8aee33054",
					"validatorMinHeightActive": 1,
					"maxHeightPrevoted": 3
				}
			},
			"output": {
				"finalizedHeight": 1,
				"preVotedConfirmedHeight": 4,
				"preVotes": {
					"1": 4,
					"2": 4,
					"3": 4,
					"4": 3,
					"5": 2,
					"6": 1
				},
				"preCommits": {
					"1": 3,
					"2": 2,
					"3": 1
				}
			}
		},
		{
			"description": "When block with height 7 is forged",
			"input": {
				"validatorName": "D3",
				"blockHeader": {
					"id": "8719647946811673230",
					"height": 7,
					"maxHeightPreviouslyForged": 3,
					"generatorPublicKey": "544d87cbf83b7c1572bb0d9f95abd5db89d0930bbb91980ea0dd7942a1cd38a3",
					"validatorMinHeightActive": 1,
					"maxHeightPrevoted": 4
				}
			},
			"output": {
				"finalizedHeight": 2,
				"preVotedConfirmedHeight": 5,
				"preVotes": {
					"1": 4,
					"2": 4,
					"3": 4,
					"4": 4,
					"5": 3,
					"6": 2,
					"7": 1
				},
				"preCommits": {
					"1": 4,
					"2": 3,
					"3": 2,
					"4": 1
				}
			}
		},
		{
			"description": "When block with height 8 is forged",
			"input": {
				"validatorName": "D4",
				"blockHeader": {
					"id": "3198191471355371895",
					"height": 8,
					"maxHeightPreviouslyForged": 4,
					"generatorPublicKey": "c2d2f82c6015fd7ed00a9e1585927a8039d63cb7afd4f7c03ad059a93c2bd6b5",
					"validatorMinHeightActive": 1,
					"maxHeightPrevoted": 5
				}
			},
			"output": {
				"finalizedHeight": 3,
				"preVotedConfirmedHeight": 6,
				"preVotes": {
					"1": 4,
					"2": 4,
					"3": 4,
					"4": 4,
					"5": 4,
					"6": 3,
					"7": 2,
					"8": 1
				},
				"preCommits": {
					"1": 4,
					"2": 4,
					"3": 3,
					"4": 2,
					"5": 1
				}
			}
		},
		{
			"description": "When block with height 9 is forged",
			"input": {
				"validatorName": "D1",
				"blockHeader": {
					"id": "1826242805484023040",
					"height": 9,
					"maxHeightPreviouslyForged": 5,
					"generatorPublicKey": "6352b9c9d2a263eaa701b53314e3021607d41e1ba6d799270f08adcba50841b7",
					"validatorMinHeightActive": 1,
					"maxHeightPrevoted": 6
				}
			},
			"output": {
				"finalizedHeight": 4,
				"preVotedConfirmedHeight": 7,
				"preVotes": {
					"1": 4,
					"2": 4,
					"3": 4,
					"4": 4,
					"5": 4,
					"6": 4,
					"7": 3,
					"8": 2,
					"9": 1
				},
				"preCommits": {
					"1": 4,
					"2": 4,
					"3": 4,
					"4": 3,
					"5": 2,
					"6": 1
				}
			}
		},
		{
			"description": "When block with height 10 is forged",
			"input": {
				"validatorName": "D2",
				"blockHeader": {
					"id": "5351644240885712040",
					"height": 10,
					"maxHeightPreviouslyForged": 6,
					"generatorPublicKey": "f7a73f303f46ada157ce3cea5ffff1290a291e255fcd26678a185fd8aee33054",
					"validatorMinHeightActive": 1,
					"maxHeightPrevoted": 7
				}
			},
			"output": {
				"finalizedHeight": 5,
				"preVotedConfirmedHeight": 8,
				"preVotes": {
					"1": 4,
					"2": 4,
					"3": 4,
					"4": 4,
					"5": 4,
					"6": 4,
					"7": 4,
					"8": 3,
					"9": 2,
					"10": 1
				},
				"preCommits": {
					"1": 4,
					"2": 4,
					"3": 4,
					"4": 4,
					"5": 3,
					"6": 2,
					"7": 1
				}
			}
		},
		{
			"description": "When block with height 11 is forged",
			"input": {
				"validatorName": "D3",
				"blockHeader": {
					"id": "5748892369479747538",
					"height": 11,
					"maxHeightPreviouslyForged": 7,
					"generatorPublicKey": "544d87cbf83b7c1572bb0d9f95abd5db89d0930bbb91980ea0dd7942a1cd38a3",
					"validatorMinHeightActive": 1,
					"maxHeightPrevoted": 8
				}
			},
			"output": {
				"finalizedHeight": 6,
				"preVotedConfirmedHeight": 9,
				"preVotes": {
					"1": 4,
					"2": 4,
					"3": 4,
					"4": 4,
					"5": 4,
					"6": 4,
					"7": 4,
					"8": 4,
					"9": 3,
					"10": 2,
					"11": 1
				},
				"preCommits": {
					"1": 4,
					"2": 4,
					"3": 4,
					"4": 4,
					"5": 4,
					"6": 3,
					"7": 2,
					"8": 1
				}
			}
		},
		{
			"description": "When block with height 12 is forged",
			"input": {
				"validatorName": "D4",
				"blockHeader": {
					"id": "7733195345837784852",
					"height": 12,
					"maxHeightPreviouslyForged": 8,
					"generatorPublicKey": "c2d2f82c6015fd7ed00a9e1585927a8039d63cb7afd4f7c03ad059a93c2bd6b5",
					"validatorMinHeightActive": 1,
					"maxHeightPrevoted": 9
				}
			},
			"output": {
				"finalizedHeight": 7,
				"preVotedConfirmedHeight": 10,
				"preVotes": {
					"1": 4,
					"2": 4,
					"3": 4,
					"4": 4,
					"5": 4,
					"6": 4,
					"7": 4,
					"8": 4,
					"9": 4,
					"10": 3,
					"11": 2,
					"12": 1
				},
				"preCommits": {
					"1": 4,
					"2": 4,
					"3": 4,
					"4": 4,
					"5": 4,
					"6": 4,
					"7": 3,
					"8": 2,
					"9": 1
				}
			}
		}
	]
}

=== LiskArchive/lisk-sdk/protocol-specs/generator_outputs/lisk_codec/block_header_decodings.json
{
	"title": "Decoding for block header types supported by lisk-codec",
	"summary": "Examples of encoding block header with lisk-codec",
	"config": {
		"network": "devnet"
	},
	"runner": "lisk_codec",
	"handler": "block_header_decodings",
	"testCases": [
		{
			"description": "Decoding of valid block header 1",
			"input": {
				"value": "08011085f6b7f60518c3faf3052220ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad2a20a665a45920422f9d417e4867efdc4fb8a04a1f3fff1fa07e998e86f7f7a27ae3322068a751863fe73b8ede8d832be628ff680d617fa15c74d00142f9025d5f37dd50388088debe014220d59386e0ae435e292fbe0ebcdb954b75ed5fb3922091277cb19f798fc5d507184a408331b5123cac056e2ec8361c56e642db0ca0e13abe33696d23d4d00ad6de844919296e87abe8e172f67fd882b4c0b1c1804b7d9075ecf975cf2631d8d7efef0c",
				"schema": {
					"$id": "/blockHeaderSchema",
					"type": "object",
					"properties": {
						"version": {
							"dataType": "uint32",
							"fieldNumber": 1
						},
						"timestamp": {
							"dataType": "uint32",
							"fieldNumber": 2
						},
						"height": {
							"dataType": "uint32",
							"fieldNumber": 3
						},
						"previousBlockID": {
							"dataType": "bytes",
							"fieldNumber": 4
						},
						"transactionRoot": {
							"dataType": "bytes",
							"fieldNumber": 5
						},
						"generatorPublicKey": {
							"dataType": "bytes",
							"fieldNumber": 6
						},
						"reward": {
							"dataType": "uint64",
							"fieldNumber": 7
						},
						"asset": {
							"dataType": "bytes",
							"fieldNumber": 8
						},
						"signature": {
							"dataType": "bytes",
							"fieldNumber": 9
						}
					},
					"required": [
						"version",
						"timestamp",
						"height",
						"previousBlockID",
						"transactionRoot",
						"generatorPublicKey",
						"reward",
						"asset"
					]
				}
			},
			"output": {
				"object": {
					"version": 1,
					"timestamp": 1590557445,
					"height": 12385603,
					"previousBlockID": "ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad",
					"transactionRoot": "a665a45920422f9d417e4867efdc4fb8a04a1f3fff1fa07e998e86f7f7a27ae3",
					"generatorPublicKey": "68a751863fe73b8ede8d832be628ff680d617fa15c74d00142f9025d5f37dd50",
					"reward": "400000000",
					"asset": "d59386e0ae435e292fbe0ebcdb954b75ed5fb3922091277cb19f798fc5d50718",
					"signature": "8331b5123cac056e2ec8361c56e642db0ca0e13abe33696d23d4d00ad6de844919296e87abe8e172f67fd882b4c0b1c1804b7d9075ecf975cf2631d8d7efef0c"
				}
			}
		},
		{
			"description": "Decoding of valid block header 2",
			"input": {
				"value": "080310ecf8b7f60518b9ff362220e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b8552a20e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b8553220acc56344dea609e80cf5d4165e46917104fe701927847fc2a5d40e37574b2b38388088debe014220eaaf9d4c65cb501c811ef812847a55513181474d734ead1b95b7e1e5b574d2234a401e65032943af975c3cdef94b1fce639645bddb29265321e0277a0f48143ef7f6f6daa1046234a09cc593969ff04d8d082edd15a4a9b90a7b8865fcd9dac44300",
				"schema": {
					"$id": "/blockHeaderSchema",
					"type": "object",
					"properties": {
						"version": {
							"dataType": "uint32",
							"fieldNumber": 1
						},
						"timestamp": {
							"dataType": "uint32",
							"fieldNumber": 2
						},
						"height": {
							"dataType": "uint32",
							"fieldNumber": 3
						},
						"previousBlockID": {
							"dataType": "bytes",
							"fieldNumber": 4
						},
						"transactionRoot": {
							"dataType": "bytes",
							"fieldNumber": 5
						},
						"generatorPublicKey": {
							"dataType": "bytes",
							"fieldNumber": 6
						},
						"reward": {
							"dataType": "uint64",
							"fieldNumber": 7
						},
						"asset": {
							"dataType": "bytes",
							"fieldNumber": 8
						},
						"signature": {
							"dataType": "bytes",
							"fieldNumber": 9
						}
					},
					"required": [
						"version",
						"timestamp",
						"height",
						"previousBlockID",
						"transactionRoot",
						"generatorPublicKey",
						"reward",
						"asset"
					]
				}
			},
			"output": {
				"object": {
					"version": 3,
					"timestamp": 1590557804,
					"height": 901049,
					"previousBlockID": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
					"transactionRoot": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
					"generatorPublicKey": "acc56344dea609e80cf5d4165e46917104fe701927847fc2a5d40e37574b2b38",
					"reward": "400000000",
					"asset": "eaaf9d4c65cb501c811ef812847a55513181474d734ead1b95b7e1e5b574d223",
					"signature": "1e65032943af975c3cdef94b1fce639645bddb29265321e0277a0f48143ef7f6f6daa1046234a09cc593969ff04d8d082edd15a4a9b90a7b8865fcd9dac44300"
				}
			}
		}
	]
}

=== LiskArchive/lisk-sdk/protocol-specs/generator_outputs/lisk_codec/cart_sample_decodings.json
{
	"title": "Decoding for a complex object",
	"summary": "Example of encoding a complex object that might exist in custom apps",
	"config": {
		"network": "devnet"
	},
	"runner": "lisk_codec",
	"handler": "cart_sample_decodings",
	"testCases": [
		{
			"description": "Decoding of object with multiple arrays",
			"input": {
				"value": "08d2091080acb8f6051864221c089edbb10210d7041801221008d70410061a09537461746520546178221c089eeda50410bf0c1801221008bf0c10071a09537461746520546178",
				"schema": {
					"$id": "/cartSample",
					"type": "object",
					"properties": {
						"orderId": {
							"dataType": "uint32",
							"fieldNumber": 1
						},
						"createdAt": {
							"dataType": "uint32",
							"fieldNumber": 2
						},
						"customerId": {
							"dataType": "uint32",
							"fieldNumber": 3
						},
						"lineItems": {
							"type": "array",
							"fieldNumber": 4,
							"items": {
								"type": "object",
								"properties": {
									"productId": {
										"dataType": "uint32",
										"fieldNumber": 1
									},
									"price": {
										"dataType": "uint32",
										"fieldNumber": 2
									},
									"quantity": {
										"dataType": "uint32",
										"fieldNumber": 3
									},
									"taxLines": {
										"type": "array",
										"fieldNumber": 4,
										"items": {
											"type": "object",
											"properties": {
												"price": {
													"dataType": "uint32",
													"fieldNumber": 1
												},
												"rate": {
													"dataType": "uint32",
													"fieldNumber": 2
												},
												"title": {
													"dataType": "string",
													"fieldNumber": 3
												}
											}
										}
									}
								}
							}
						}
					}
				}
			},
			"output": {
				"object": {
					"orderId": 1234,
					"createdAt": 1590564352,
					"customerId": 100,
					"lineItems": [
						{
							"productId": 5008798,
							"price": 599,
							"quantity": 1,
							"taxLines": [
								{
									"price": 599,
									"rate": 6,
									"title": "State Tax"
								}
							]
						},
						{
							"productId": 9008798,
							"price": 1599,
							"quantity": 1,
							"taxLines": [
								{
									"price": 1599,
									"rate": 7,
									"title": "State Tax"
								}
							]
						}
					]
				}
			}
		}
	]
}
